alertmanager:
  ## Prometheus alertmanager ingress
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: self-signing-issuer
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    extraLabels: {}
    hosts:
    - alertmanager.mystartup.io
    extraPaths: []
    tls:
    - secretName: prometheus-alerts-tls
      hosts:
      - alertmanager.mystartup.io

server:
  ## Prometheus server ingress
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: self-signing-issuer
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    extraLabels: {}
    hosts:
    - prometheus.mystartup.io
    extraPaths: []
    tls:
    - secretName: prometheus-server-tls
      hosts:
      - prometheus.mystartup.io

pushgateway:
  ## Pushgateway ingress
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: self-signing-issuer
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
    - pushgateway.mystartup.io
    extraPaths: []
    tls:
    - secretName: prometheus-alerts-tls
      hosts:
      - pushgateway.domain.com
