apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-cd
spec: {}
