apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nginx-ingress
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: argocd
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: promethues
spec: {}
status: {}
