{{ range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.argocd.namespace }}
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .server }}
  project: {{ .project }}
  source:
{{ toYaml .source | indent 4 }}
    path: {{ .path }}
    repoURL: {{ .repository }}
    targetRevision: {{ .revision }}
  syncPolicy:
    automated:
      prune: true
---
{{ end }}